# docker-compose.yml for developer support
#
# Usage:
#
#  docker-compose up -d
#
# Port allocation scheme:
#   3113    The PostgreSQL database
#   4200    The Angular UI (not part of this project)
#   8113    The covidcode back-end server (not managed by docker-compose)
#   8181    The Keycloak server, in direct access (e.g. for administering with a browser)

version: "3"

# To purge all state, stop all containers and say
#
#    docker volume rm covidcode_dbdata
#
# This will erase the PostgreSQL database. Then start everything again
volumes:
  dbdata:

services:

  db:
    image: "postgres:11"
    container_name: "dp3t_postgres"
    ports:
      - "3113:5432"
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./devsupport/keycloak/create-database-and-user.sql:/docker-entrypoint-initdb.d/create-keycloak-database-and-user.sql

  keycloak:
    image: jboss/keycloak
    container_name: "keycloak"
    environment:
      # https://hub.docker.com/r/jboss/keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: masterPassword
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_IMPORT: /tmp/realm-bag-pts-localhost.json
    volumes:
      - ./devsupport/keycloak/realm-bag-pts-localhost.json:/tmp/realm-bag-pts-localhost.json
    ports:
      - "8181:8080"
