spring:
  flyway:
    locations: classpath:db/migration/common

authcodegeneration:
  jwt:
    issuer: "http://localhost:8113"
    token-validity: 300000
    privateKey: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDT5jbu96Mf5UvkGrp3sj0Spoh0Cf664/ksSs5fOGM6ZFRh4IkjDRokfEu7nWbGSYftrfVLAatL1At+Jc+yEe29RKFzAHjatmLSCb59BtWoJAHa3+gPm2Essk2F93iAuRiWPVeJ3uz1fqPCYG9Gca65YSzOvlPUN7+Nih/0DeJOfrtq138c5Thv+YgJbzih1p2T+9iEZ9QqE77Xf0oNFJCpWcW8Fu2JKCHuDPYCjXdEHlONClHUskICqmheppsaSqdSIXxbj9ZylHUqTp/zLsL7m91Z0/Fy3ZUgYCKJSopCaWJSZJIq4YEM5OMwjArCB1/UZyWzARsdjj5j8cRYc+BdAgMBAAECggEARLKLNrgkM5AEJaSgtXOcpzJEZNJkujR0sO5jr605RlIGpWDFNQ7nXdLKPr4N9tUZ822Fa9bTsRbCzxf1GPcFC2p3qTAK/mVI7m1oS2Ju3D8oNsyGkKDARVxdE8SiVaEsnnCus60JR6HR94+KI91xVvpxK2m7Bb85I+sW5umlZ+rI59XgnP9q3EtOxnC4GQ/QfTjFIgAZHUJwzh0SZ+I2GPXLw9WkFGyxgW6wKaNQOUz/jjJyPNTl3jg0cW9kcHrviyHZK+IPVwQINj7JEzRZ5rCXBjEBE8ht1g1vu7QPQD1x7ZGCrjWAXfr01rNSJMPNEIi1CEaVbz63j6ewUVZV4QKBgQD7GNOnDorqimmGO+sJ6LV3DqrBa2TPCfclcgSiKBu+A/B1nBBLAsNVXN59BTtYHilj+Xhdt1cmOHBo9a0ZCrqHjU6xWyl9iOxh8rhpE0FZ/3g3aWM7aII+SyheMrFtfBh4XrvH5ZJLrzJiiGg+TDTuFApksmb6qf/SE+ZQFZNRaQKBgQDYCXKs051beqn1kHWVwTcb1UTqrTuclgnNZ3sPKjVwvGCqUIRsyWZOV8E7PFeU2F9Ek/3nvLw5pTY+F5Aq0Tfaxt3yS7nRhRfWLL4wMyezYrE/qPFN5L8bhejcuSjRieIWXQU8vMI0+YIIV45JmP44M9cjbcrkPuzvl2soY8+E1QKBgQCOC2NgM9feCmLbrvWta1mMel2agXhLryWCp1d7rBjVi0DyJ1EIPg3mMl0ieF0z4gwkJDI1QcwpMPBWT/SWH/2ZRRTpO9riyxx95GLx/hSQJvcI0bNzHhHfz4CMmTzJ5NOq9FxiHrp92iQ0nVnrNA0VSXz/rfSXhKfVXbCCSVJHUQKBgQCe+CzTMhCLvTKNiZSM8xW7PG8vBPRloB5scGYkXZnfcC7thLw9VOIcagS9swR7edB4pTHkMYSMIp9Mh4hFiZjBOy8c2U5N99L3fgsharMfFFN7lbSi7d0Wwq38pZ98uSqN7DsrW3bJBoUB4HPKgnMnJjZ8UpFG7WrqTxDCMtgEVQKBgFFFy9AypTsQgdQf1VWdUGX7uJ8TYTuhMVzcOThtQeuVnTEqp9gUyuarc6xOL2i7wD6cdnb48NhqJ66r/F8bxMAUMOaElrAo7IIZXfSJdpPVFMwGVz022lk//XdjA/VcJv5tNnBoKP29cRCkf6WU1SEdlyoVu/vzPNMGbNZMyt8s"
  monitor:
    prometheus:
      user: "prometheus"
      password: "{noop}secret"

jeap:
  security:
    oauth2:
      resourceserver:
        authorization-server:
          issuer: "http://localhost:8180"
          jwk-set-uri: "http://localhost:8180/.well-known/jwks.json"

ha-authcode-generation-service:
  allowed-origin: "http://localhost:4200"

## Uncomment the following to increase logging; then issue
## `mvn compile` to copy this configuration under target/
# server:
#   tomcat:
#     basedir: /tmp
#     accesslog:
#       enabled: true
#       directory: /dev
#       prefix: stdout
#       buffered: false
#       suffix:
#       file-date-format:
#
# logging:
#   level:
#     org.apache.tomcat: DEBUG
#     org.apache.catalina: DEBUG
#     org:
#       apache:
#         tomcat: DEBUG
#         catalina: DEBUG
