spring:
  flyway:
    locations: classpath:db/migration/common

authcodegeneration:
  monitor:
    prometheus:
      user: "prometheus"
      password: "{noop}secret"
  service:
    keycloak:
      realm: "bag-pts"
      uri: http://localhost
      masterPassword: secret
      clientSecret: secret

jeap:
  security:
    oauth2:
      resourceserver:
        authorization-server:
          issuer: "http://localhost:8180"
          jwk-set-uri: "http://localhost:8180/.well-known/jwks.json"

ha-authcode-generation-service:
  allowed-origin: "http://localhost:4200"
