authcodegeneration:
  monitor:
    prometheus:
      user: "prometheus"
      password: ${vcap.services.ha_prometheus_dev.credentials.password}
  service:
    keycloak:
      realm: "bag-pts"
      uri: https://identity-r.bit.admin.ch
      masterPassword: ${vcap.services.keycloak_dev.credentials.masterPassword}
      clientSecret: ${vcap.services.keycloak_dev.credentials.clientSecret}

jeap:
  security:
    oauth2:
      resourceserver:
        authorization-server:
          issuer: "https://identity-r.bit.admin.ch/realms/bag-pts"

ha-authcode-generation-service:
  allowed-origin: "https://www.covidcode-d.admin.ch"
